### ISSUE TITLE
Run Jasmine Unit Tests in the Browser

### ISSUE THREAD

**Issue by ghost** [xolvio/jasmine-unit#18]
I'd like to run my existing Jasmine client suit in the browser. I use Angular.JS, so this is necessary. I saw that the mocha-web velocity package already has the capability to run client tests in the browser. I would suggest the same approach for the jasmine-unit package. I will try to implement it next month.

**EDIT:** This is in a separate package: https://github.com/Sanjo/meteor-jasmine
#### Checklist
- [X] Include Jasmine 2.0 for client tests
- [X] Embed Jasmine Runner like the [mocha-web](https://github.com/mad-eye/meteor-mocha-web/) package does it
- [X] Write Velocity Reporter for Jasmine (see [ConsoleReporter](https://github.com/pivotal/jasmine/blob/master/src/console/ConsoleReporter.js) as example)
#### Additional Info
- Jasmine has a [standalone distribution](http://jasmine.github.io/2.0/introduction.html#section-Standalone_Distribution)
- Jasmines's [boot.js](http://jasmine.github.io/2.0/boot.html) can be customized. Here we can add the Velocity Reporter.

**Comment by alanning** [comment]
Hi Sanjo,

One difference between jasmine-unit and mocha-web is that jasmine-unit is running outside the Meteor context whereas mocha-web runs within a regular Meteor app.  

Would a test framework like mocha-web but with jasmine syntax solve your requirements?

**Comment by ghost** [comment]
For my client unit tests it's fine that they run outside the Meteor context with stubbed Meteor.

For the server unit tests (that doesn't exist yet) I am not sure if in-context running is needed but I think it would make testing easier. Has Jasmine a limitation that it cannot run in the Meteor context or was this a implementation decision for the package?

**Comment by alanning** [comment]
I would think the easiest way to get your tests running would be to make an Angular.JS stub.  Then you would probably be able to use jasmine-unit as is.  Would that do it for you?  If you could describe a bit more of what requirements you'd need to get your existing test suite running we could help more.

A jasmine-integration test package (think mocha-web with jasmine syntax) would also do what you need, I think, but that's farther down the road.

Re: the Meteor context, it was a conscious design choice that this package run outside the Meteor context rather than any limitation of Jasmine.  Generally all unit testing frameworks will be out-of-context so that the tests can remain pure and run as fast as possible.  Once you have outside libs included then its more correct to call them integration tests and in-context probably makes the most sense there.

**Comment by ghost** [comment]
Unfortunately it is not possible to stub Angular.JS, because the Dependency Injection part of Angular.JS is needed. At least when you want to write tests in the way how Angular.JS suggests it.
I started a separate Jasmine test runner for velocity that uses Jasmine 2.0 and runs in context on the client like mocha-web does.
I can merge the package later with yours if that has benefits for users that want to use Jasmine for all kinds of tests (unit, integration and maybe end-to-end). I also use Jasmine for end-to-end tests with [Protractor](https://github.com/angular/protractor).

One feature I really like in Jasmine is the spies functionality. That would still be missing even if you can write mocha-web tests with the same syntax.

**Comment by alanning** [comment]
Nice!  I'd recommend naming it something like jasmine-web since that seems to work for mocha-web.

Separate packages are the way to go since the in-context vs out-of-context plumbing is quite different.  

The mirroring functionality that velocity offers will probably be helpful in isolating the tests from the real code.  At least with mocha-web the tests have to be in with the main app code to work properly so in order to keep them from getting packaged up in production, velocity copies the while app, sticks the tests in, then the reporter executed them in the browser.

Also be sure to make an announcement in the velocity-core google group to let others know about your project.

**Comment by ghost** [comment]
Ok, thanks for your help. I will announce the package when it is usable.
