### ISSUE TITLE
Auto package stubber

### ISSUE THREAD

**Issue by ghost** [xolvio/jasmine-unit#3]
After the meteor-stub is loaded and before any user stubs and any meteor code being loaded, we could do the following:
1. Scan the package.js of every package in the app directory
2. For each Package.export('theExportedObject')
   
   a. Scan that package's files and find theExportedObject
   
   b. Look for all methods on theExportedObject and stub them with an empty function
   
   c. Drill deep into any objects on theExportedObject, and stub methods in there

The theory here is that we'll be able to get most cases covered so the unit testing will load up first time without the user needed to stub the ***\* out of the packages they include.

**Comment by alanning** [comment]
Would this really be useful?  It seems like automatically stubbing packages wouldn't help much because in order for the unit tests to pass the package in use would have to actually _do_ something useful too.  So the users would have to make custom stubs for that package function anyways.

I just did a small test with the velocity example project:

`1. $ mrt add moment`
`2. leaderboard.coffee`

``` coffee
if Meteor.isServer
  root = exports ? this
  root.cincoDeMayo = -> 
    moment("2014-05-05T09:30:30.000").format("MMM, DD YYYY")
  console.log root.cincoDeMayo
```

`3. stubs/package-stub.js`

``` js
moment = function () {
  return {
    format: function () {
      return ""
    }
  }
}
```

`4. tests/leaderboard-rtd-unit.js`

``` js
    describe("moment package", function () {

      it("is stubbed properly", function () {
        var may5 = cincoDeMayo()
        console.log('XXX', typeof may5)
        expect(may5).toBe("May, 05 2014");
      });

    });
```

Output of running tests:

```
Failures:
1) moment package is stubbed properly
Message:
Expected '' to be 'May, 05 2014'.
```

In order for the test to pass, I need to write a custom stub for `moment().format()`...

**Comment by xolvio** [comment]
So the purpose of auto stubbing is to allow the user's meteor code to run statically, as opposed to automatically create spies.

If you have a package the user depends on, say iron-router, and the app code has something like:

```
Router.map(function() {
    this.route('home', {path: '/'})
    this.route('about');
});
```

Without stubbing Router.map to be an empty function, starting up the app code (vm.runInContext) will fail because Router doesn't exit.

In the test the user would still have to use spies and what have you to assert the expected behavior and so fourth.

On a side note, iron-router's map function would actually require a stub and not just a spy as we're interested in what happened at the app's startup (just like Meteor.startup and xxx.template.events). In this case, after auto-pacakge-stubbing, we'd apply a proper iron-router stub.

It's actually quite a lot of hard work getting unit testing to really work with Meteor and it's due to the startup-dependencies. Any framework that taps in to startup configuration would actually require a more involved stub.

**Comment by alanning** [comment]
Ok, gotcha.  Thanks for the explanation.

This is a bit of a hairy problem.  I see a few ways of approaching it:
- statically analyze the package source and build stubs (hardest)
- statically analyze the app's Meteor.startup code and build stubs (hard)
- load packages and then stub (easiest)

I'd expect loading the packages then stubbing to be the easiest.  We'd lose most of the speed benefit of unit testing compared to running in-context but by stubbing after loading we'd maintain isolation of the unit test code from issues in the packages themselves.

Any suggestions on how to load the packages, maybe based on whatever mocha-web is doing?

**Comment by xolvio** [comment]
Sorry I missed your question!

So I have another option. Not so kosher but could just work :)

What about trying to do the loading in a try/catch clause and dynamically building a stub from undefined exceptions at loading time?

That would allow the so to at least load up in a stubbed-context. Should also be pretty fast.

Thoughts?

**Comment by alanning** [comment]
Yeah, that's one I had considered but I discarded it in favor of the `load the packages and then stub` option.  Reason being that I think we'd have to re-load the code each time an undefined was found, which would hurt performance, so in that case why not just load the packages directly and walk the resulting objects?

What do you think about having Meteor load the packages as normal, walk the package objects to build the stub, re-load the app with packages stubbed?

Any suggestions about how to do the `load the packages as normal` part?

**Comment by SamHatoum** [comment]
Hmm... You have access to an in-context app in [main.js](https://github.com/xolvio/velocity-jasmine-unit/blob/master/main.js) before [rerunTests](https://github.com/xolvio/velocity-jasmine-unit/blob/master/main.js#L106) is executed. You could run your static analysis in here, create a dynamic-stub-helper.js, which jasmine-node would load automatically (any file like xxxx-helper.js is auto loaded).

**Comment by SamHatoum** [comment]
On the try/catch solution, I still think it may have some legs without a performance hit. Consider the [vm.runInContext](https://github.com/xolvio/velocity-jasmine-unit/blob/master/lib/coffee-require.js#L73) we're using for coffee files. This currently just loads up a compiled coffee/raw js file as a string and runs it in the vm. We could wrap it with a try/catch dynamically here and if it fails, there's no reloading since the file is already loaded as a string and is still in memory. We'd stub as needed and then re-run _vm.runInContext_. 

The change here would be to also load non-coffee in the same way as above (string first). Perhaps there's a way to extend node's require to do this stuff but to start we could try the above. 

I'll attempt this route on a new branch and you can continue down the static analysis route. We can then compare our learnings and go from there.

I hope we nail this, it would be so cool that this would always work on startup. Once the app is loaded statically out-of-context, I think it's fair then to expect a developer to spy/mock/stub when they're writing tests.

**Comment by xolvio** [comment]
I tried this last night and it's not trivial! The errors coming from the VM don't have line numbers as the code is being loaded as a string. It can solve for "Reference Error: moment is not defined" but after that, it becomes tough. For example, moment is a constructor and the exception can't really distinguish between that and an object, and object depths is not easy to see either.

Perhaps a combination of try/catch plus code analysis might do the trick but I'll hold back until you have have results.

**Comment by alanning** [comment]
Static analysis is also not trivial.  Loading meteor packages as normal, walking the object graphs and building stubs, then using stubs in actual app seems like it would be the easiest. 

What do you think? Any suggestions on where to start there?

**Comment by SamHatoum** [comment]
Something like: 
- Read the packages file in .meteor, then for each package look at the package.js file and look for api.export('xxxxx');
- Walk that object in the meteor context (both client  server) and build the stub
- Pass that stub to the non-meteor context as a helper file on the file system, in a .stubs directory (we can [add this to the jasmine-cli runner](https://github.com/xolvio/velocity-jasmine-unit/blob/master/main.js#L34) to see it)
- OPTIONAL: Only rebuild that auto-stub file if packages file changes - Perhaps create a hash and call the helper the hash maybe. So the file would be called 8743b52063cd84097a65d1633f5c74f5-helper.js and you'd compare the hash to save you walking the packages again. We can optimize this per package even if this works out

**Comment by alanning** [comment]
Cool.  For step 2, how do we run a vm with the meteor stuff in-context?

**Comment by SamHatoum** [comment]
Ah. Before [this line runs](https://github.com/xolvio/velocity-jasmine-unit/blob/master/main.js#L108), you can walk the object as you're in-context here (server side of course).

**Comment by alanning** [comment]
Ok, thanks.  I'll work with that. 

Any ideas on doing the same for the client side?  If we're in context before that line then that also means the app has been bundled (dev version, at least) and we'd have access to load the client-side resources and do the same graph-walk/stubbing?

**Comment by SamHatoum** [comment]
Indeed we do have a loaded client. I envisage we can do this:
- Load the walker into the client
- Post back the walker results to a meteor method
- When both the client and server have walked the walk, create the stub file

Caching is looking more and more like a necessary step now!

I'd wait until we know that the results of the server walker before porting it to the client as that's a (little) more involved.

**Comment by alanning** [comment]
Jest, a new js testing framework built on jasmine and from Facebook, also does auto mocking. They do it the way we're heading by loading dependencies, walking graph, and using stubs/mocks for actual unit tests. :-)

http://facebook.github.io/jest/docs/automatic-mocking.html#content

**Comment by SamHatoum** [comment]
That's AWESOME! Nice find :+1:

**Comment by SamHatoum** [comment]
Do you think we can repurpose it?

**Comment by alanning** [comment]
Yeah, definitely can gank stuff.  Better yet, find some way to use it directly.  Have to look more into it. 

It's made to work with commonjs modules but if they haven't already exposed the parts we need I'd be pretty sure they would if we asked.

**Comment by alanning** [comment]
Woohoo!  Got a simple auto-stubber working!  Check out the 'auto-stub' branch to play with it.

**Comment by SamHatoum** [comment]
Can't wait to try this!!

**Comment by alanning** [comment]
In process of extracting out stubbing code.  New smart package to perform auto-stubbing can be found here:  https://github.com/alanning/meteor-package-stubber

NOTE: jasmine-unit `auto-stub` branch not updated yet

**Comment by alanning** [comment]
Process complete!  
- jasmine-unit v0.1.8 up on atmosphere.  
- velocity example app updated
