### ISSUE TITLE
Is it possible to test private functions with Jasmine-unit ?

### ISSUE THREAD

**Issue by vjau** [xolvio/jasmine-unit#32]
Hi everyone,
i'm new to unit testing, so sorry in advance for my newbie question.
Since meteor file are enclosed in an IIFE, all function bound to a variable declared with var are private and can't be accessed outside, unless they are explicitely exposed with the revealing pattern or something else.
Does that mean that jasmine-unit can only test global (reachable) functions ?
Thank you in advance.

**Comment by ghost** [comment]
No, it is not possible and not necessary.
Normally you don't need to test private functions because testing the public functions will automatically ensure that the private functions do what they should, because private functions are used by the public functions. If that is not the case, you should consider your module and class structure (split bigger modules into smaller modules for example).

**Comment by ghost** [comment]
This approach also avoids coupling your tests with you implementation details. You can easily refactor your implementation without needing to change your tests. As long as the API of your component keeps the same.

**Comment by vjau** [comment]
Ok, thank you.

**Comment by sanidz** [comment]
spyOn<any>(component, 'privateMethod').and.returnValue('');

**Comment by sokre90** [comment]
You can access the private method with bracket notation. It works just fine but might not be "clean".

`const fixture = TestBed.createComponent(ProductSearchDialogComponent);`
`const component = fixture.componentInstance;`
`const filtered = component['_filter']('dummy arg', ['dummy arr item 0', 'dummy arr item 1']);`
`expect(filtered.length).toBe(0);`
