### ISSUE TITLE
Option for bringing in package instead of stubbing?

### ISSUE THREAD

**Issue by davidworkman9** [xolvio/jasmine-unit#38]
Is there currently a way to load a package instead of stubbing it? My code relies on `_` heavily for adding functionality to models (using `_.extend`). Because `_.extend` is stubbed as an empty function my code doesn't work as expected.

In a similar situation I have another app that is entirely made of packages. Each piece of functionality is it's own package, so testing it with jasmine-unit is impossible. It would be nice if I could flag packages to be loaded in, rather than stubbed. I'm open to other suggestions as well.

**Comment by ghost** [comment]
Nope, surprisingly not. I will add this now.

**Comment by davidworkman9** [comment]
Awesome :)

**Comment by ghost** [comment]
Ok, now I know why. jasmine-unit doesn't know how to load packages. (= It's not so straight forward to implement as I first thought)

For client code you can use my jasmine package (`mrt add jasmine`). It runs in the app context, so everything of your app is available. Server side in-context testing is coming soon.

**Comment by alanning** [comment]
`jasmine-unit` (and unit tester's in general) run 'out-of-context' which means that packages and Meteor aren't actually loaded.  This is by design since with unit-testing you generally want to have the tests isolate a very specific piece of functionality and want them to be as fast as possible (so you can have a lot of them).  It's more important for larger test suites.  It's also why stubbing is required and why unit testing is generally more complicated than running an 'in-context' framework.

If you need full packages to actually be loaded, using an 'in-context' test framework like `jasmine` is the right way to go.

If all you need is certain functionality, such as underscore's `extend` function, the way you do this with `jasmine-unit` is by copying the relevant code to a custom stub in your `tests` directory.

In your case, I'd suggest copying the entire underscore code to `tests/underscore-stub.js`.  `jasmine-unit` will load user stubs before any tests are executed.

You can read more about it here: https://github.com/xolvio/jasmine-unit#stubs

**Comment by davidworkman9** [comment]
Do you have any suggestions for unit testing apps that use the [Package Only App Structure](http://www.manuel-schoebel.com/blog/meteorjs-package-only-app-structure-with-mediator-pattern)?

**Comment by SamHatoum** [comment]
I find underscore is more of an extension to the JS language than an external dependency, so stubbing it would be much more painful than including it in my opinion.

I think we should include an option for jasmine-unit to: `use_underscore` or `use_lodash` and it will do put the actual minified version of those libraries on the users behalf (maybe even with a version).

This can be done manually today as @alanning suggested above by just putting underscore as a underscore-stub.js

**Comment by SamHatoum** [comment]
@davidworkman9 I'm working on [a solution called packaglets](https://github.com/xolvio/velocity/issues/77) that allows you to isolate packages for integration testing. This won't allow you to do unit-testing yet but might it will be of value for package-only apps that don't have an option to use Velocity yet.

When using the Mediator pattern, you'll be using multiple packages, in which case you'll need to run an integration test anyway. Jasmine / mocha-web both allow you to do this on the client.

I'll have a think about getting packages into the jasmine-unit VM. @Sanjo is also working on migrating unit-testing into the single jasmine package using some new logic so I'll get together with him and see if there's anything we can conjure.
