### ISSUE TITLE
Move stubbing to velocity service

### ISSUE THREAD

**Issue by alanning** [xolvio/jasmine-unit#4]
Let other unit testing frameworks request loading of Meteor internal, template, package, and user-provided stubs.

Would this be as simple as having the stubbing routines be velocity Meteor methods?  Or is there something else that needs to be done regarding the execution context of the individual test frameworks?

**Comment by xolvio** [comment]
If an app is able to call a Meteor method, it would make that app a meteor app. The way rtd-unit does non-contextual tests is by having the rtd-unit in-context runner (main.js) running a command-line jasmine-node, and then transforming the xml results at the end. Options I see are:
- Running a mocha command line and using the same mechanism above
- Running a mocha command line and using streaming instead of waiting until the end and parsing result files
- Using node's [vm.runInNewContext()](http://nodejs.org/api/vm.html#vm_script_runinnewcontext_sandbox)

I'm also thinking of renaming rtd-unit to velocity-jasmine-unit to make it clearer, allowing a naming convention on meteorite to happen: velocity-mocha-unit [(like karma do it)](https://github.com/karma-runner/)

Thoughts?

**Comment by alanning** [comment]
Thumbs up on rename. 

Good point on meteor method = meteor app. 

vm.runInNewContext seems to work for the coffee script runner.

I'm still fuzzy on how velocity is actually doing the black magic of integrating test frameworks.  What do you think is the best way to achieve an "inContext" / "auto-stub" flag?

**Comment by xolvio** [comment]
Renamed!

velocity is just syncing a collection with the file system using gulp, and then looking at the end of a file to see what framework it's destined for. That's all!

See this issue for what I think it the best discriminator. https://github.com/xolvio/velocity-jasmine-unit/issues/3 (the filename + package basically)

**Comment by alanning** [comment]
OK, I think I understand now...communication is done through MongoDB!  

Meteor app developers add velocity and individual test framework packages.  Velocity enumerates the files that need to be tested and stores them in a MongoDB collection.  The test framework packages are in charge of running themselves and just watch the same MongoDB collection to get the path to the appropriate test files to execute.

Once the framework packages run their tests they report results to MongoDB collection, which velocity watches and does stuff with.

(Is this right?  For some reason I had it in my mind that velocity was executing the individual test frameworks somehow but this is much simpler.)

**Comment by xolvio** [comment]
that's exactly right. Velocity can then focus on dishing out the tests. Interestingly, test frameworks will run in parallel, which therefore implies, we could add cloud-helper runners ;)

**Comment by alanning** [comment]
Cool.  (Cloud helper runners would be awesome!)

So how do you think we should expose the stubbing functionality to the individual test frameworks?

**Comment by SamHatoum** [comment]
I'm leaning towards an NPM module that any framework can pull in. 

```
require('stubbed-meteor-context')
```

Inside here, the module would export everything to the root object, [something like this](https://github.com/mhevery/jasmine-node/blob/master/lib/jasmine-node/index.js#L202).

What do you think?

**Comment by alanning** [comment]
Extracted meteor stubs to separate NPM package.

NPM package - https://www.npmjs.org/package/meteor-stubs
Source - https://github.com/alanning/meteor-stubs
